version: "3.1"

services:
  database:
    image: postgres:14
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_DB=alex_bot"
    ports:
      - "5441:5432"
